export default function Data(){
    const TableDetails=[{d1:"First Name",d2:"Last Name",d3:"Course",d4:"Country",d5:"Profile"},
                        {d1:"James",d2:"Kim",d3:"IT",d4:"Korea",d5:"View"},
                        {d1:"Emily",d2:"Jones",d3:"Computer Engineering",d4:"USA",d5:"View"},
                        {d1:"Michael",d2:"Smith",d3:"Engineering",d4:"UK",d5:"View"},
                        {d1:"Sophia",d2:"Miller",d3:"Mathematics",d4:"France",d5:"View"},
                        {d1:"Daniel",d2:"Brown",d3:"Business",d4:"Canada",d5:"View"},
                        {d1:"Olivia",d2:"Johnson",d3:"Design",d4:"Australia",d5:"View"},
                        {d1:"William",d2:"Wilson",d3:"Physics",d4:"Germony",d5:"View"},
                        {d1:"Ava",d2:"Davis",d3:"Medicine",d4:"Japan",d5:"View"},
                        {d1:"Liam",d2:"Taylor",d3:"Psychology",d4:"India",d5:"View"},
                        {d1:"Emma",d2:"Thomas",d3:"Environmental Science",d4:"Brazil",d5:"View"},
                        {d1:"Noah",d2:"White",d3:"Political Science",d4:"USA",d5:"View"},
                        {d1:"Isabella",d2:"Anderson",d3:"Sociology",d4:"South Africa",d5:"View"},
                        {d1:"Mason",d2:"Moore",d3:"Economics",d4:"Russia",d5:"View"},
                        {d1:"Aria",d2:"Martin",d3:"History",d4:"Italy",d5:"View"},
                        {d1:"Ethan",d2:"Clark",d3:"Chemistry",d4:"Korea",d5:"View"},
                        {d1:"Grace",d2:"Lewis",d3:"Nursing",d4:"Swedan",d5:"View"},
                        {d1:"Logan",d2:"Hill",d3:"Astronomy",d4:"USA",d5:"View"},
                        {d1:"Mia",d2:"Ward",d3:"Linguistics",d4:"Spain",d5:"View"}
    ]
    return(
        <>
        <table border={1} style={{border:'1px solid black',fontSize:'30px',borderCollapse:'collapse'}}>
            <tr>
                <th>{TableDetails[0].d1}</th>
                <th>{TableDetails[0].d2}</th>
                <th>{TableDetails[0].d3}</th>
                <th>{TableDetails[0].d4}</th>
                <th>{TableDetails[0].d5}</th>
            </tr>
            <tr>
                <td>{TableDetails[1].d1}</td>
                <td>{TableDetails[1].d2}</td>
                <td>{TableDetails[1].d3}</td>
                <td>{TableDetails[1].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[2].d1}</td>
                <td>{TableDetails[2].d2}</td>
                <td>{TableDetails[2].d3}</td>
                <td>{TableDetails[2].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[3].d1}</td>
                <td>{TableDetails[3].d2}</td>
                <td>{TableDetails[3].d3}</td>
                <td>{TableDetails[3].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[4].d1}</td>
                <td>{TableDetails[4].d2}</td>
                <td>{TableDetails[4].d3}</td>
                <td>{TableDetails[4].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[5].d1}</td>
                <td>{TableDetails[5].d2}</td>
                <td>{TableDetails[5].d3}</td>
                <td>{TableDetails[5].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[6].d1}</td>
                <td>{TableDetails[6].d2}</td>
                <td>{TableDetails[6].d3}</td>
                <td>{TableDetails[6].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[7].d1}</td>
                <td>{TableDetails[7].d2}</td>
                <td>{TableDetails[7].d3}</td>
                <td>{TableDetails[7].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[8].d1}</td>
                <td>{TableDetails[8].d2}</td>
                <td>{TableDetails[8].d3}</td>
                <td>{TableDetails[8].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[9].d1}</td>
                <td>{TableDetails[9].d2}</td>
                <td>{TableDetails[9].d3}</td>
                <td>{TableDetails[9].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[10].d1}</td>
                <td>{TableDetails[10].d2}</td>
                <td>{TableDetails[10].d3}</td>
                <td>{TableDetails[10].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[11].d1}</td>
                <td>{TableDetails[11].d2}</td>
                <td>{TableDetails[11].d3}</td>
                <td>{TableDetails[11].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[12].d1}</td>
                <td>{TableDetails[12].d2}</td>
                <td>{TableDetails[12].d3}</td>
                <td>{TableDetails[12].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[13].d1}</td>
                <td>{TableDetails[13].d2}</td>
                <td>{TableDetails[13].d3}</td>
                <td>{TableDetails[13].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[14].d1}</td>
                <td>{TableDetails[14].d2}</td>
                <td>{TableDetails[14].d3}</td>
                <td>{TableDetails[14].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[15].d1}</td>
                <td>{TableDetails[15].d2}</td>
                <td>{TableDetails[15].d3}</td>
                <td>{TableDetails[15].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[16].d1}</td>
                <td>{TableDetails[16].d2}</td>
                <td>{TableDetails[16].d3}</td>
                <td>{TableDetails[16].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[17].d1}</td>
                <td>{TableDetails[17].d2}</td>
                <td>{TableDetails[17].d3}</td>
                <td>{TableDetails[17].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
            <tr>
                <td>{TableDetails[18].d1}</td>
                <td>{TableDetails[18].d2}</td>
                <td>{TableDetails[18].d3}</td>
                <td>{TableDetails[18].d4}</td>
                <td><button>{TableDetails[1].d5}</button></td>
            </tr>
        </table>
        </>
    )
}